name: peg
channels:
  - defaults
  - conda-forge
pip:
  - absl-py
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - astunparse
  - async-generator
  - atari-py
  - attrs
  - babel
  - backcall
  - bleach
  - cachetools
  - cffi
  - chardet
  - click
  - cloudpickle
  - contextvars
  - cycler
  - cython
  - dataclasses
  - decorator
  - defusedxml
  - dill
  - dm-env
  - dm-tree
  - entrypoints
  - fasteners
  - flatbuffers
  - future
  - gast
  - glfw
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - grpcio
  - gym
  - h5py
  - idna
  - imageio
  - imageio-ffmpeg
  - immutables
  - importlib-metadata
  - ipdb
  - ipykernel
  - ipython
  - ipython-genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonschema
  - jupyter
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - jupyter-server
  - jupyterlab
  - jupyterlab-pygments
  - jupyterlab-server
  - jupyterlab-widgets
  - keras-preprocessing
  - keyboard
  - kiwisolver
  - labmaze
  - llvmlite
  - lxml
  - markdown
  - markupsafe
  - matplotlib
  - mistune
  - mujoco-py
  - multiprocess
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - numba
  - numpy
  - numpy-quaternion
  - oauthlib
  - opencv-python
  - opensimplex
  - opt-einsum
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - prometheus-client
  - prompt-toolkit
  - protobuf
  - ptyprocess
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pygame
  - pyglet
  - pygments
  - pyopengl
  - pyparsing
  - pyquaternion
  - pyrsistent
  - python-dateutil
  - pytz
  - pyzmq
  - qtconsole
  - qtpy
  - requests
  - requests-oauthlib
  - rsa
  - ruamel-yaml
  - ruamel-yaml-clib
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - six
  - sniffio
  - tabulate
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow-estimator
  - tensorflow
  - tensorflow-probability
  - termcolor
  - terminado
  - testpath
  - threadpoolctl
  - toml
  - torch
  - tornado
  - tqdm
  - traitlets
  - typeguard
  - typing-extensions
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - widgetsnbextension
  - wrapt
  - zipp